default_language_version:
  python: python3.12

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: check-builtin-literals
      - id: check-byte-order-marker
      - id: check-case-conflict
      - id: check-executables-have-shebangs
      - id: check-json
      - id: check-merge-conflict
      - id: check-symlinks
      - id: check-yaml
      - id: debug-statements
      - id: end-of-file-fixer
      - id: mixed-line-ending
      - id: trailing-whitespace
        args: [ --markdown-linebreak-ext=md ]
  - repo: https://github.com/psf/black
    rev: 24.8.0
    hooks:
      - id: black
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v3.13.0
    hooks:
      - id: reorder-python-imports
  - repo: https://gitlab.com/PyCQA/pydocstyle/
    rev: 6.1.1
    hooks:
      - id: pydocstyle
